version: "3.8"
services:

    app:
        container_name: app_container
        build:
            context: ./
            dockerfile: Dockerfile
        command: poetry run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        env_file:
            - .env-dev
        volumes:
            - ./app:/src/app

    postgres:
        container_name: postgres_container
        image: postgres:latest
        ports:
            - 5432:5432
        env_file:
            - .env-dev
        volumes:
            - ./app:/src/app