"""add session_id

Revision ID: 11f3ead85ec1
Revises: fbd11149e1ad
Create Date: 2025-05-30 10:36:59.206327

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11f3ead85ec1"
down_revision: Union[str, None] = "fbd11149e1ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session_log", sa.Column("session_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session_log", "session_id")
    # ### end Alembic commands ###
